version: '3.7'

services:
  nginx:
    image: nginx:stable
    container_name: scan-nginx
    working_dir: /symbiota
    volumes:
      - ./:/symbiota
      - /data/disk/scan-imglib:/imglib
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    networks:
      - scan

  php:
    build: ./docker/php-fpm
    container_name: scan-php
    working_dir: /symbiota
    volumes:
      - ./:/symbiota
      - /data/disk/scan-imglib:/imglib
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:ro
      - ./docker/php-fpm/www-overrides.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:ro
    networks:
      - scan

  mariadb:
    image: mariadb:10.3
    container_name: scan-mariadb
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./config/schema-1.0/utf8:/docker-entrypoint-initdb.d:ro
      - /data/disk/dockervols/scan-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symbiota
    ports:
      - 3306:3306
    networks:
      - scan

  solr:
    build: ./docker/solr
    container_name: scan-solr
    environment:
      SOLR_JAVA_MEM: "-Xms8g -Xmx8g"
    volumes:
      - ./docker/solr/solr.in.sh:/opt/solr/bin/solr.in.sh:ro
      - /data/disk/dockervols/scan-solr:/opt/solr/server/solr
    networks:
      - scan

networks:
  scan:

