version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /symbiota
    volumes:
      - ./:/symbiota
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  php:
    build: ./docker/php-fpm
    container_name: php
    working_dir: /symbiota
    volumes:
      - ./:/symbiota
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  mysql:
    image: mariadb:10.3
    container_name: mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./config/schema-1.0/utf8:/docker-entrypoint-initdb.d
      - scan-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symbiota
    ports:
      - 3308:3306

  redis:
    image: redis:5
    container_name: redis

volumes:
  scan-db:
    name: scan-db

